main: org.mcwonderland.uhc.WonderlandUHC
name: WonderlandUHC
version: ${pluginVersion}
author: LU__LU
softdepend: [ LuckPerms, Chunky, DiscordSRV ]
api-version: 1.21

commands:
  backpack:
    aliases: [bp]
    description: 開啟隊伍背包。
    usage: /<command> [玩家]
  border:
    description: 強制收縮邊界。
    usage: /<command> <大小>
  config:
    aliases: [cfg]
    description: 查看遊戲相關設定。
  disableitems:
    description: 查看禁止使用的物品。
  finish:
    description: 完成目前等待中的設定輸入。
  giveall:
    description: 給予所有場上的玩家指定數量的物品。
    usage: /<command> <物品類型> <數量>
  practice:
    description: 加入或退出練習模式。
    usage: /<command>
  reconnect:
    description: 重新連結 Discord 語音頻道。
  respawn:
    description: 復活玩家。
    usage: /<command> <玩家>
  scenarios:
    description: 查看本場使用的特殊模式。
  sendcoords:
    aliases: [scs]
    description: 向隊友發送座標。
  setspawn:
    description: 設定大廳重生點。
  spectoggle:
    description: 切換觀戰模式。
  staff:
    description: 切換管理員模式。
  stats:
    description: 查看玩家數據。
    usage: /<command> [玩家]
  team:
    description: 管理隊伍。
    usage: /<command> <chat|create|disband|invite|join|leave|kick|list|promote|public|settings> [參數]
  tohead:
    description: 將主手普通金蘋果轉換為金頭顱。
  topkills:
    aliases: [killtop, kt]
    description: 查看擊殺數排行榜。
  uhc:
    description: 管理 UHC 主流程。
    usage: /<command> <reload|choose|edit|regen|resetteam|sethost|splitteam|switchteam|stop|tp|start|tutorial> [參數]
  viewheal:
    aliases: [h]
    description: 查看玩家血量。
    usage: /<command> <玩家>
  whitelist:
    aliases: [wl]
    description: 管理本場遊戲白名單。
    usage: /<command> <add|remove|list|clear> [玩家...]

permissions:
  wonderland.uhc.admin:
    children:
      wonderland.uhc.host: true
      wonderland.uhc.command.uhc.reload: true

  wonderland.uhc.host:
    children:
      wonderland.uhc.bypass.join.configuring: true
      wonderland.uhc.item.settings: true
      wonderland.uhc.moderator: true
      wonderland.uhc.command.border: true
      wonderland.uhc.command.uhc.choose: true
      wonderland.uhc.command.uhc.splitteam: true
      wonderland.uhc.command.uhc.resetteam: true
      wonderland.uhc.command.uhc.switchteam: true
      wonderland.uhc.command.uhc.tutorial: true
      wonderland.uhc.command.uhc.edit: true
      wonderland.uhc.command.uhc.sethost: true
      wonderland.uhc.command.uhc.stop: true
      wonderland.uhc.command.uhc.tp: true
      wonderland.uhc.command.uhc.regen: true
      wonderland.uhc.command.uhc.start: true
      wonderland.uhc.command.whitelist: true
      wonderland.uhc.command.setspawn: true
      wonderland.uhc.host.seebackpack: true

  wonderland.uhc.moderator:
    children:
      wonderland.uhc.bypass.join.full: true
      wonderland.uhc.bypass.join.started: true
      wonderland.uhc.bypass.join.whitelist: true
      wonderland.uhc.command.staff: true
      wonderland.uhc.command.giveall: true
      wonderland.uhc.command.respawn: true
      wonderland.uhc.seespectatorchat: true

  wonderland.uhc.bypass.kick.death:
    default: true

  wonderland.uhc.command.config:
    default: true
  wonderland.uhc.command.scenarios:
    default: true
  wonderland.uhc.command.disableitems:
    default: true
  wonderland.uhc.command.sendcoords:
    default: true
  wonderland.uhc.command.spectoggle:
    default: true
  wonderland.uhc.command.stats:
    default: true
  wonderland.uhc.command.topkills:
    default: true
  wonderland.uhc.command.viewheal:
    default: true
  wonderland.uhc.command.practice:
    default: true
  wonderland.uhc.command.reconnect:
    default: true
  wonderland.uhc.command.uhc.tutorial:
    default: true

  wonderland.uhc.command.team.chat:
    default: true
  wonderland.uhc.command.team.create:
    default: true
  wonderland.uhc.command.team.disband:
    default: true
  wonderland.uhc.command.team.invite:
    default: true
  wonderland.uhc.command.team.join:
    default: true
  wonderland.uhc.command.team.kick:
    default: true
  wonderland.uhc.command.team.leave:
    default: true
  wonderland.uhc.command.team.list:
    default: true
  wonderland.uhc.command.team.promote:
    default: true
  wonderland.uhc.command.team.public:
    default: true
  wonderland.uhc.command.team.settings:
    default: true

  wonderland.uhc.team.settings.name:
    default: true
  wonderland.uhc.team.settings.character:
    default: true
  wonderland.uhc.team.settings.color:
    default: true

  wonderland.uhc.command.respawn:
    default: op
