package org.mcwonderland.uhc.application.world;

public enum CenterScoreReason {
    OCEAN_RATIO_TOO_HIGH,
    WATER_RATIO_TOO_HIGH,
    SECTION_WATER_TOO_HIGH,
    ADJACENT_SECTION_WATER_TOO_HIGH,
    CENTER_WATER_TOO_HIGH,
    CENTER_STANDABLE_RATIO_TOO_LOW,
    CENTER_HEIGHT_SPREAD_TOO_HIGH,
    CENTER_CLIFF_RATIO_TOO_HIGH,
    TOO_MANY_LOW_SECTIONS,
    FOREST_RATIO_TOO_HIGH,
    DENSE_FOREST_RATIO_TOO_HIGH,
    HIGHLAND_RATIO_TOO_HIGH,
    EXTREME_HIGHLAND_RATIO_TOO_HIGH
}
